services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitmetrics-app
    env_file:
      - .env
    expose:
      - "3001"
    restart: unless-stopped

  nginx:
    image: docker.1ms.run/library/nginx:1.31.0-alpine3.23
    container_name: gitmetrics-nginx
    depends_on:
      - app
    ports:
      - "8569:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
